--[[
Copyright (c) 2018 Eric Liu.
All Rights Reserved.
--]]

local argParse = require("argparse");

--[[
    Function to handle building and parsing of command line arguments
--]]
local function ParseArgs()
    local parser = argParse("speedtest.lua",
    "Command line interface for testing internet bandwidth using speedtest.net.",
    "For more information, see https://github.com/egliu/speedtest-lua");
    parser:help_max_width(80);
    parser:option("--no-download",
                "Do not perform download test");
    parser:option("--no-upload",
                "Do not perform upload test");
    parser:option("--bytes", 
                "Display values in bytes instead of bits. Does "..
                "not affect the image generated by --share, nor "..
                "output from --json or --csv");
    parser:option("--share", 
                "Generate and provide a URL to the speedtest.net "..
                "share results image, not displayed with --csv");
    parser:option("--simple", 
                "Suppress verbose output, only show basic "..
                "information");
    parser:option("--csv", 
                "Suppress verbose output, only show basic "..
                "information in CSV format. Speeds listed in "..
                "bit/s and not affected by --bytes");
    parser:option("--csv-delimiter", 
                "Single character delimiter to use in CSV "..
                "output. Default ','");
    parser:option("--csv-header", 
                "Print CSV headers");
    parser:option("--json", 
                "Suppress verbose output, only show basic "..
                "information in JSON format. Speeds listed in "..
                "bit/s and not affected by --bytes");
    parser:option("--list", 
                "Display a list of speedtest.net servers "..
                "sorted by distance");
    parser:option("--server", 
                "Specify a server ID to test against. Can be "..
                "supplied multiple times");
    parser:option("--exclude", 
                "Exclude a server from selection. Can be "..
                "supplied multiple times");
    parser:option("--mini", 
                "URL of the Speedtest Mini server");
    parser:option("--source", 
                "Source IP address to bind to");
    parser:option("--timeout", 
                "HTTP timeout in seconds. Default 10");
    parser:option("--secure", 
                "Use HTTPS instead of HTTP when communicating "..
                "with speedtest.net operated servers");
    parser:option("--no-pre-allocate", 
                "Do not pre allocate upload data. Pre allocation "..
                "is enabled by default to improve upload "..
                "performance. To support systems with "..
                "insufficient memory, use this option to avoid a "..
                "MemoryError");
    parser:option("--version", 
                "Show the version number and exit");

    local args = parser:parse();
end

ParseArgs();